// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package jsonparser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[String-0]
	_ = x[Number-1]
	_ = x[False-2]
	_ = x[True-3]
	_ = x[Null-4]
	_ = x[LeftBrace-5]
	_ = x[RightBrace-6]
	_ = x[LeftParen-7]
	_ = x[RightParen-8]
	_ = x[Comma-9]
	_ = x[Colon-10]
	_ = x[EOF-11]
}

const _TokenType_name = "StringNumberFalseTrueNullLeftBraceRightBraceLeftParenRightParenCommaColonEOF"

var _TokenType_index = [...]uint8{0, 6, 12, 17, 21, 25, 34, 44, 53, 63, 68, 73, 76}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
